"""remove member model

Revision ID: 32332c089f1d
Revises: cacf13fad617
Create Date: 2023-04-11 18:15:23.289249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32332c089f1d'
down_revision = 'cacf13fad617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True)
    )
    # ### end Alembic commands ###
