"""create member foreignkey

Revision ID: 9c851d44c496
Revises: cbb1e9ce8255
Create Date: 2023-04-11 18:33:29.756856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c851d44c496'
down_revision = 'cbb1e9ce8255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('member_of_project', 'member', ['member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('member_of_project', type_='foreignkey')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
