"""add picture_url to Project

Revision ID: ba9d00d03a9c
Revises: bdef2e7ec7ed
Create Date: 2023-04-08 20:44:44.050875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9d00d03a9c'
down_revision = 'bdef2e7ec7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=260), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
